export const images = {
  logo: require('./logo1.png'),
  facebook: require('./facebook.png'),
  tiktok: require('./tiktok.png'),
  youtube: require('./youtube.png'),
  linkIn: require('./linkIn.png'),
  logo2: require('./logo2.png'),
  certificate: require('./certificate.png'),
  DMCA: require('./DMCA.png'),
  Print: require('./printnow.png'),
  women: require('./Group 30.png'),
  w01: require('./01.png'),
  w02: require('./02.png'),
  w03: require('./03.png'),
  w04: require('./04.png'),
  calendar: require('./calendar.png'),
  box: require('./box.png'),
  bag: require('./bag.png'),
  standee: require('./standee.png'),
  handbook: require('./handbook.png'),
  all: require('./all.png'),
  brochure: require('./brochure.png'),
  card: require('./card.png'),
  news: require('./news.png'),
  product: require('./Product.png'),
  ab01: require('./Rectangle 38.png'),
  ab02: require('./Rectangle 39.png'),
  ab03: require('./Rectangle 40.png'),
  ab04: require('./Group 100.png'),
  unique: require('./Rectangle 73.png'),
  support: require('./support-image.png'),
  trend: require('./Rectangle 77.png'),
};
export const banner = {
  banner1: require('./Artboard 1.png'),
  banner2: require('./Artboard 2.png'),
  banner3: require('./Artboard 3.png'),
  banner4: require('./Artboard 4.png'),
};
export const background = {
  aboutBG: require('./aboutus-background.png'),
  categoryBG: require('./category-background.png'),
};
export const aboutImg = {
  aboutValue1: require('./about-value-01.png'),
  aboutValue2: require('./about-value-02.png'),
  aboutValue3: require('./about-value-03.png'),
  aboutValue4: require('./about-value-04.png'),
  aboutValue5: require('./about-value-05.png'),
  aboutValue6: require('./about-value-06.png'),
  women: require('./Group 114.png'),
  vision: require('./Ellipse 11.png'),
};
export const categoryImg = {
  cate1: require('./calendar.png'),
  cate2: require('./catalouge.png'),
  cate3: require('./profile.png'),
  cate4: require('./brochure.png'),
  cate5: require('./box icon.png'),
  cate6: require('./standee.png'),
  cate7: require('./backdrp icon.png'),
  cate8: require('./flyer.png'),
  cate9: require('./invite.png'),
  cate10: require('./voucher.png'),
  cate11: require('./sticker.png'),
  cate12: require('./label.png'),
  cate13: require('./bag.png'),
  cate14: require('./card.png'),
  cate15: require('./menu.png'),
  cate16: require('./boxes.png'),
  cate17: require('./booth icon.png'),
  cate18: require('./photobooth.png'),
  cate19: require('./award.png'),
  cate20: require('./handbook.png'),
  cate21: require('./luckymoney.png'),
  cate22: require('./mail.png'),
};
export const designImg = {
  des1: require('./Design-page/Rectangle 79.png'),
  des2: require('./Design-page/Rectangle 79 (1).png'),
  des3: require('./Design-page/Rectangle 79 (2).png'),
  des4: require('./Design-page/Rectangle 79 (3).png'),
  des5: require('./Design-page/Rectangle 79 (4).png'),
  des6: require('./Design-page/Rectangle 79 (5).png'),
  des7: require('./Design-page/Rectangle 85.png'),
  des8: require('./Design-page/Rectangle 85 (1).png'),
  des9: require('./Design-page/Rectangle 85 (2).png'),
  des10: require('./Design-page/Rectangle 85 (3).png'),
  des11: require('./Design-page/Rectangle 85 (4).png'),
  des12: require('./Design-page/Rectangle 85 (5).png'),
  des13: require('./Design-page/Rectangle 85 (6).png'),
  des14: require('./Design-page/Rectangle 85 (7).png'),
  des15: require('./Design-page/Rectangle 85 (8).png'),
  des16: require('./Design-page/Rectangle 85 (9).png'),
  des17: require('./Design-page/Rectangle 85 (10).png'),
  des18: require('./Design-page/Rectangle 85 (11).png'),
  des19: require('./Design-page/Rectangle 85 (12).png'),
  des20: require('./Design-page/Rectangle 85 (13).png'),
  des21: require('./Design-page/Rectangle 85 (14).png'),
  des22: require('./Design-page/Rectangle 85 (15).png'),
  des23: require('./Design-page/Rectangle 85 (16).png'),
  des24: require('./Design-page/Rectangle 85 (17).png'),
  des25: require('./Design-page/Rectangle 78.png'),
};
export const logoImg = {
  logo1: require('./Logo-page/logo.png'),
  logo2: require('./Logo-page/image 19.png'),
  logo3: require('./Logo-page/banner.png'),
  logo4: require('./Logo-page/Rectangle 92.png'),
  logo5: require('./Logo-page/comma.png'),
};
export const policyImg = {
  pol1: require('./Policy-page/Group.png'),
  pol2: require('./Policy-page/Group (1).png'),
  pol3: require('./Policy-page/Group (2).png'),
  pol4: require('./Policy-page/Group (3).png'),
  pol5: require('./Policy-page/Group (4).png'),
};
export const categoryIcon = {
  cate1: require('./Category-menu/lịch icon.svg'),
  cate2: require('./Category-menu/catalogue icon.svg'),
  cate3: require('./Category-menu/profile icon.svg'),
  cate4: require('./Category-menu/brochure icon.svg'),
  cate5: require('./Category-menu/hộp icon.svg'),
  cate6: require('./Category-menu/standee icon.svg'),
  cate7: require('./Category-menu/backdrop icon.svg'),
  cate8: require('./Category-menu/tờ rơi icon.svg'),
  cate9: require('./Category-menu/voucher icon.svg'),
  cate10: require('./Category-menu/sticker icon.svg'),
  cate11: require('./Category-menu/nhãn icon.svg'),
};
